name: Deploy to Firebase Hosting on push and schedule
on:
  push:
    branches:
      - main
  schedule:
    # Her 45 minutdan awtomatiki işleýär
    - cron: '*/45 * * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VPN Gate-den iň täze CSV-ni alyp public/vpngate.csv üstüne ýazýar
      - name: Fetch Latest VPN Gate CSV
        run: |
          mkdir -p public
          curl -s "http://www.vpngate.net/api/iphone/" -o public/vpngate.csv

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DISASTER_2AD1A }}'
          channelId: live
          projectId: disaster-2ad1a
