name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main  # Eger kodyňyz 'master' branch-da bolsa, 'main' deregine 'master' ýazyň

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Eger proýektiňizde build almak gerek bolsa (meselem npm run build), aşakdaky liniýanyň başyndaky #-i aýyryň:
      # - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DISASTER_2AD1A }}'
          channelId: live
          projectId: disaster-2ad1a
